apiVersion: apps/v1
kind: Deployment
metadata:
  name: xpensia
  namespace: default
  labels:
    app: xpensia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xpensia
      tier: frontend
  template:
    metadata:
      labels:
        app: xpensia
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: xpensia-app:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: xpensiaconfigmapv1.0
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
