apiVersion: v1
kind: Service
metadata:
  name: xpensia
  namespace: default
  labels:
    app: xpensia
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: flask
  selector:
    app: xpensia
    tier: frontend
  type: LoadBalancera
